### ISSUE TITLE
遍历算法描述

### ISSUE THREAD

**Issue by xudafeng** [macacajs/NoSmoke#1]
- 深度遍历算法描述
- 生命周期定义

**Comment by SamuelZhaoY** [comment]
**// Structure of Node**
class Node {
  __weakRef var parent:Node
  __weakRef var children:[Node]
  var done:Bool
  var digest:String
}

**// Models**
var currentNode:Node
var nodeTree:[Node] 

**// Initialization**
void function init() {
  var firstNode = currentPage()
  traverse(firstNode)
}

**// Depth-First Traversing**
void function traverse(node:Node) {
  var source = getSource(node)

  // Scan whether source contains specific requirements from yml
  // If so, only those specific actions are recorded as child nodes for the current action.
  // else, all clickable types of elements are recorded as child nodes for the current action.

  var children = filterChildern(node, configuration)
  node.children = children
    
    
}

**Comment by xudafeng** [comment]
https://github.com/macacajs/NoSmoke/pull/3
