### ISSUE TITLE
事件使用原生的就够了

### ISSUE THREAD

**Issue by xudafeng** [macacajs/NoSmoke#15]
http://xudafeng.github.io/nodejs/events.html#events_events_eventemitter

"wolfy87-eventemitter": "^5.2.2", 可以去掉了

**Comment by SamuelZhaoY** [comment]
![macaca-android](https://user-images.githubusercontent.com/8198256/31303578-988f5db2-ab42-11e7-8b96-52175fe4ba92.gif)
![macaca-ios](https://user-images.githubusercontent.com/8198256/31303576-98897564-ab42-11e7-9a12-36e5aaf5161d.gif)
![web-pc](https://user-images.githubusercontent.com/8198256/31303577-988df9c2-ab42-11e7-8c60-1bd456cedddd.gif)

**Comment by SamuelZhaoY** [comment]
![image](https://user-images.githubusercontent.com/8198256/31303704-aa26c68a-ab44-11e7-9346-02db403edc48.png)
