### ISSUE TITLE
Android环境下无法遍历

### ISSUE THREAD

**Issue by liwanyin** [macacajs/NoSmoke#27]
1、运行命令后，模拟器上可以安装APK并打开APK，但是cmd提示直接遍历结束，如下：
  --> GET /favicon.ico 200                                                                                               
initialize crawler                                                                                                       
-----> Crawling Finished <-----                                                                                          
(node:4352) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: socketed.disconne
cted is not a function                                                                                                   

2、我的配置文件如下，请帮忙看看是否有问题，谢谢：
# 1. Initialization option
desiredCapabilities:
 # isWaitActivity: true
 # activity: 'LoginActivity'
  deviceName: 'emulator-5554'
  app: 'https://npmcdn.com/android-app-bootstrap@latest/android_app_bootstrap/build/outputs/apk/android_app_bootstrap-debug.apk'
  platformName: android

# 2. Crawling option
crawlingConfig:
  platform: 'Android'
  targetElements:
    loginAccount:
      actionType  : 2
      searchValue : 'please input username'
      actionValue : '中文+Test+12345678'
    loginPassword:
      actionType  : 2
      searchValue : 'please input password'
      actionValue : '111111'
    loginButton:
      actionType  : 1
      searchValue : 'Login'
    alertConfirm:
      actionType  : 1
      searchValue : 'yes'
  clickTypes:
   - 'android.widget.ImageView'
   - 'android.widget.TextView'
   - 'android.widget.Button'
   - 'StaticText'
   - 'Button'
  editTypes:
   - 'android.widget.EditText'
   - 'TextField'
   - 'SecureTextField'
  tabBarTypes:
   - 'TabBar'
  exclusiveTypes:
   - 'NavigationBar'
  navigationBackKeyword:
   - '返回'
   - '取消'

**Comment by SamuelZhaoY** [comment]
Android  -> android ， 模拟器版本请用 android 5.0 以及以上

**Comment by SamuelZhaoY** [comment]
https://github.com/macacajs/NoSmoke/issues/28  与该问题重叠
