### ISSUE TITLE
win10 安卓默认配置遍历报错

### ISSUE THREAD

**Issue by Archer456** [macacajs/NoSmoke#28]
win10环境  利用cmd命令行执行的

`D:\NoSmoke>npm run dev

> nosmoke@0.1.0 dev D:\NoSmoke
> nodemon ./bin/nosmoke -s

[nodemon] 1.11.0

[nodemon] watching: *.* any time, enter `rs`
[nodemon] starting `node ./bin/nosmoke -s`
udid: undefined
>> NoSmoke start at: http://169.254.209.237:5678
----> silent mode <-------
  <-- GET /
{ stats:
   { suites: 0,
     tests: 0,
     passes: 3,
     pending: 0,
     failures: 0,
     start: 2017-10-23T05:57:36.342Z,
     passPercent: 50,
     pendingPercent: 0,
     other: 0,
     hasOther: false,
     skipped: 1,
     hasSkipped: true,
     duration: 14523,
     end: 2017-10-23T05:57:36.342Z },
  suites:
   { title: '',
     ctx: {},
     suites: [],
     tests: [],
     pending: [],
     _beforeEach: [],
     _beforeAll: [],
     _afterEach: [],
     _afterAll: [],
     root: true,
     _timeout: 2000,
     _enableTimeouts: true,
     _slow: 75,
     _retries: -1,
     delayed: false,
     _events: { 'pre-require': [] },
     _eventsCount: 1,
     uuid: 'xxxxxxxxxxx',
     fullFile: '',
     file: '',
     passes: [],
     failures: [],
     skipped: [],
     totalTests: 0,
     totalPasses: 0,
     totalFailures: 0,
     totalPending: 0,
     totalSkipped: 0,
     duration: 0,
     _totalTime: 14523 },
  current:
   { image: 'https://macacajs.github.io/macaca-logo/svg/monkey.svg',
     list: [ [Object], [Object], [Object] ] } } { name: 'macaca-reporter',
  fileName: 'index.html',
  assetsInline: true,
  dataAttr: 'data-output',
  configAttr: 'config-output',
  distDir: 'D:\\NoSmoke',
  socket: { server: 'http://169.254.209.237:56788' } }
>> reporter generated: D:\NoSmoke\reports\index.html
  --> GET / 200
socket connected
(node:17832) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): FetchError: invalid json response body at http://localhost:3456/wd/hub/session reason: Unexpected token I in JSON at position 0`

`C:\Users\cmd>macaca server --verbose
>> index.js:18:12 [master] pid:2376 webdriver server start with config:
 { port: 3456,
  verbose: true,
  always: true,
  ip: '169.254.209.237',
  host: 'cmd',
  loaded_time: '2017-10-23 14:00:10' }
>> middlewares.js:17:10 [master] pid:2376 base middlewares attached
>> router.js:127:10 [master] pid:2376 router set
>> webdriver sdk launched
>> responseHandler.js:11:12 [master] pid:2376 Recieve HTTP Request from Client[2017-10-23 14:00:19]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformName":"android","isWaitActivity":true,"activity":"LoginActivity","app":"https://npmcdn.com/android-app-bootstrap@latest/android_app_bootstrap/build/outputs/apk/android_app_bootstrap-debug.apk"}}
>> session.js:47:10 [master] pid:2376 Creating session, sessionId: 7fdde3a0-b039-45df-b4cc-75c0735a3d25.
>> get C:\Users\cmd\.macaca-temp\android_app_bootstrap-debug.apk from cache
>> sha:9656cdf14170f899681bebe9d58a1de4
>> helper.js:208:12 [master] pid:2376 Using local app form C:\Users\cmd\.macaca-temp\android_app_bootstrap-debug.apk
>> responseHandler.js:56:12 [master] pid:2376 Send Error Respone to Client: Error: Command failed: D:\Android\android-sdk-windows/platform-tools/adb -s 192.168.60.101:5555 shell "pm install -r "/data/local/tmp/com.macaca.android.testing""
Failure [-26: Package com.macaca.android.testing new target SDK 18 doesn't support runtime permissions but the old target SDK 25 does.]

>> responseHandler.js:62:14 [master] pid:2376 Error: Command failed: D:\Android\android-sdk-windows/platform-tools/adb -s 192.168.60.101:5555 shell "pm install -r "/data/local/tmp/com.macaca.android.testing""
Failure [-26: Package com.macaca.android.testing new target SDK 18 doesn't support runtime permissions but the old target SDK 25 does.]

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

  Error: Command failed: D:\Android\android-sdk-windows/platform-tools/adb -s 192.168.60.101:5555 shell "pm install -r "/data/local/tmp/com.macaca.android.testing""
  Failure [-26: Package com.macaca.android.testing new target SDK 18 doesn't support runtime permissions but the old target SDK 25 do  .]

      at ChildProcess.exithandler (child_process.js:206:12)
      at emitTwo (events.js:106:13)
      at ChildProcess.emit (events.js:191:7)
      at maybeClose (internal/child_process.js:877:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)`

默认配置改为了android的 也就是
desiredCapabilities:
  platformName: 'android'
  isWaitActivity: true
  activity: 'LoginActivity'
  app: 'https://npmcdn.com/android-app-bootstrap@latest/android_app_bootstrap/build/outputs/apk/android_app_bootstrap-debug.apk'

模拟器 用的是Genymotion 7.0.0 的系统镜像，API24    

服务端报了一个如上日志的错，
 Error: Command failed: D:\Android\android-sdk-windows/platform-tools/adb -s 192.168.60.101:5555 shell "pm install -r "/data/local/tmp/com.macaca.android.testing""
  Failure [-26: Package com.macaca.android.testing new target SDK 18 doesn't support runtime permissions but the old target SDK 25 do

**Comment by Archer456** [comment]
sorry   脚本配置改造问题 已经自己搞定了   3Q

**Comment by Archer456** [comment]
上述问题 应该是android sdk api 24的 问题。 换了个6.0.0的镜像，将配置改为如下：
`desiredCapabilities:
platformName: 'android'
  isWaitActivity: true
  activity: 'LoginActivity'
  app: 'https://npmcdn.com/android-app-bootstrap@latest/android_app_bootstrap/build/outputs/apk/android_app_bootstrap-debug.apk'

# 2. Crawling option
crawlingConfig:
  platform: 'Android'
  targetElements:
    loginAccount:
      actionType  : 2
      searchValue : 'please input username'
      actionValue : '中文+Test+12345678'
    loginPassword:
      actionType  : 2
      searchValue : 'please input password'
      actionValue : '111111'
    loginButton:
      actionType  : 1
      searchValue : 'Login'
    alertConfirm:
      actionType  : 1
      searchValue : 'yes'

  exclusivePattern: 'pushView/popView/cookie/userAgent:/Mozilla/cookie:/setTitle/Macaca Test Swipe API/'
  clickTypes:
    - 'android.widget.ImageView'
    - 'android.widget.TextView'
    - 'android.widget.Button'
  editTypes:
    - 'android.widget.EditText'
  tabBarTypes:
    - 'android.widget.TabWidget'
`
看日志：
![image](https://user-images.githubusercontent.com/18392901/31876330-c9eae68c-b804-11e7-9c1a-f55cf2bf8166.png)

现象是 换起了那个app的 登录界面 但是不执行 
loginAccount:
      actionType  : 2
      searchValue : 'please input username'
      actionValue : '中文+Test+12345678'

以下

**Comment by SamuelZhaoY** [comment]
`# 1. Initialization option
desiredCapabilities:
  platformName: 'android'
  isWaitActivity: true
  activity: 'LoginActivity'
  app: 'https://npmcdn.com/android-app-bootstrap@latest/android_app_bootstrap/build/outputs/apk/android_app_bootstrap-debug.apk'

#  Web Configuration
#  platformName: 'Desktop'
#  browserName: 'Chrome'
#  url: 'https://macacajs.github.io'

#  iOS Configuration
#  platformName: 'iOS'
#  deviceName: 'iPhone 6 Plus'
#  app: 'https://npmcdn.com/ios-app-bootstrap@latest/build/ios-app-bootstrap.zip'

#  Android Configuration
#  platformName: 'android'
#  isWaitActivity: true
#  activity: 'LoginActivity'
#  app: 'https://npmcdn.com/android-app-bootstrap@latest/android_app_bootstrap/build/outputs/apk/android_app_bootstrap-debug.apk'

# 2. Crawling option
crawlingConfig:
  platform: 'android'
  targetElements:
      loginAccount:
        actionType  : 2
        searchValue : 'please input username'
        actionValue : '中文+Test+12345678'
      loginPassword:
        actionType  : 2
        searchValue : 'please input password'
        actionValue : '111111'
      loginButton:
        actionType  : 1
        searchValue : 'Login'
      alertConfirm:
        actionType  : 1
        searchValue : 'yes'
  exclusivePattern: 'pushView/popView/cookie/userAgent:/Mozilla/cookie:/setTitle/Macaca Test Swipe API/'
  clickTypes:
    - 'android.widget.ImageView'
    - 'android.widget.TextView'
    - 'android.widget.Button'
  editTypes:
    - 'android.widget.EditText'
  tabBarTypes:
    - 'android.widget.TabWidget'
...

# Web Configuration
#  platform: 'PC-Web'
#  clickTypes:
#    - 'a'
#  editTypes:
#    - 'input'

#  # Android Configuration
#  platform: 'android'
#  exclusivePattern: 'pushView/popView/cookie/userAgent:/Mozilla/cookie:/setTitle/Macaca Test Swipe API/'
#  clickTypes:
#    - 'android.widget.ImageView'
#    - 'android.widget.TextView'
#    - 'android.widget.Button'
#  editTypes:
#    - 'android.widget.EditText'
#  tabBarTypes:
#    - 'android.widget.TabWidget'

#  # iOS Configuration
#  platform: 'iOS'
#  exclusivePattern: 'pushView/popView/cookie/userAgent:/Mozilla/cookie:/setTitle/Macaca Test Swipe API/'
#  clickTypes:
#    - 'StaticText'
#    - 'Button'
#  editTypes:
#    - 'TextField'
#    - 'SecureTextField'
#  horizontalScrollTypes:
#    - 'PageIndicator'
#  verticalScrollTypes:
#    - 'ScrollView'
#  tabBarTypes:
#    - 'TabBar'
#  exclusiveTypes:
#    - 'NavigationBar'
#  navigationBackKeyword:
#    - '返回'
#    - '取消'`

参考最新配置， 更新一下 macaca-android， 以及macac reporter

**Comment by SamuelZhaoY** [comment]
platform: 'Android'  -> 'android'
