### ISSUE TITLE
win10    electron配置也报错

### ISSUE THREAD

**Issue by Archer456** [macacajs/NoSmoke#30]
---
# 1. Initialization option
desiredCapabilities:
  platformName: 'Desktop'
  browserName: 'electron'
  url: 'https://macacajs.github.io'
  
crawlingConfig:
  clickTypes:
    - 'a'
  editTypes:
    - 'input'
...

initialize crawler
(node:16108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token < in JSON at position 0

![image](https://user-images.githubusercontent.com/18392901/31880118-2c714096-b812-11e7-8d0e-c645c626d6cd.png)

**Comment by SamuelZhaoY** [comment]
---
# 1. Initialization option
desiredCapabilities:
  platformName: 'Desktop'
  browserName: 'Electron'
  url: 'https://macacajs.github.io'

#  Web Configuration
#  platformName: 'Desktop'
#  browserName: 'Electron'
#  url: 'https://macacajs.github.io'

#  iOS Configuration
#  platformName: 'iOS'
#  deviceName: 'iPhone 6 Plus'
#  app: 'https://npmcdn.com/ios-app-bootstrap@latest/build/ios-app-bootstrap.zip'

#  Android Configuration
#  platformName: 'android'
#  isWaitActivity: true
#  activity: 'LoginActivity'
#  app: 'https://npmcdn.com/android-app-bootstrap@latest/android_app_bootstrap/build/outputs/apk/android_app_bootstrap-debug.apk'

# 2. Crawling option
crawlingConfig:
  platform: 'PC-Web'
  clickTypes:
    - 'a'
  editTypes:
    - 'input'
...
