### ISSUE TITLE
补充单测

### ISSUE THREAD

**Issue by xudafeng** [macacajs/NoSmoke#37]
- [ ] 单测覆盖率低，提升到90%，部分分支有明显错误 (如 https://github.com/macacajs/NoSmoke/commit/009fe0676581989a030d2c1adb85f0bcf7cb188d#diff-47198da0ebe64f1ce98b2b700f225a3eR39)

**Comment by xudafeng** [comment]
https://coveralls.io/github/macacajs/NoSmoke

**Comment by SamuelZhaoY** [comment]
done, coverage 82%
