### ISSUE TITLE
Could you given a complete demo for *.yml

### ISSUE THREAD

**Issue by zhangpeng23796** [macacajs/NoSmoke#44]
for example:targetElements？

当EditText包裹在TextInputLayout里时，“请输入密码”的提示在xml中找不到，该如何找这个元素？是否可以根据resource-id查找？

![image](https://user-images.githubusercontent.com/26616673/35510931-0a05cd2c-0535-11e8-8f65-e8e51e1a78af.png)

**Comment by xudafeng** [comment]
@SamuelZhaoY 建个目录，把各平台常见的几个.yml 配置都给出来吧

**Comment by SamuelZhaoY** [comment]
每个平台的详细配置方法参考这里https://github.com/macacajs/NoSmoke/blob/master/docs/1.%20%20configuration-templates.md
