### ISSUE TITLE
需要钩子订制和函数覆盖的相关模板

### ISSUE THREAD

**Issue by yangjunjian** [macacajs/NoSmoke#45]
请大神抽空补充下，在某类似微信的app上执行，YML配置不够用。。

**Comment by SamuelZhaoY** [comment]
看看这个 https://github.com/macacajs/NoSmoke/blob/master/docs/4.%20writing-your-hooks.md

**Comment by xingtao555** [comment]
@SamuelZhaoY 地址404了，有新的吗
