### ISSUE TITLE
运行demo出错udid ： undefined

### ISSUE THREAD

**Issue by boyxiaohua** [macacajs/NoSmoke#53]
>> port: 5678 was occupied, changed port: 5680
>> server.js:15:12 [master] pid:13397 server start with config:
 { port: 5680,
  verbose: true,
  hooks: './public/hook.js',
  config: './public/crawler.config.yml',
  ip: '172.23.40.184',
  host: 'yangxiaohuadeMacBook-Pro.local',
  loaded_time: '2018-03-28 18:41:47' }
udid: undefined

配置文件没有进行修改过，就想运行下demo

**Comment by SamuelZhaoY** [comment]
安卓适配问题，没安装模拟器.
