### ISSUE TITLE
NoSmoke支持设置控件的优先级别吗

### ISSUE THREAD

**Issue by boyxiaohua** [macacajs/NoSmoke#54]
比如进行到下单页面，必须点击同意协议才能点击下单这种场景

**Comment by SamuelZhaoY** [comment]
targetElements: 中声明的为高优先级触发控件， 如果一个页面中没有match 到targetElements: 中的元素，所有element 优先级一样.  需要进一步定制的话，可以使用hook

**Comment by SamuelZhaoY** [comment]
https://github.com/macacajs/NoSmoke/blob/master/lib/crawler/crawler.js#L447   你所说的text 其实已经包含了 text, label, name, content 等等的几种属性了.  resource-id 是安卓端特有的一个能力，目前优先级较低，但欢迎PR
