### ISSUE TITLE
配置文件参数文档在哪里可以看

### ISSUE THREAD

**Issue by mizhdi** [macacajs/NoSmoke#58]
![image](https://user-images.githubusercontent.com/3582887/45020771-7621a480-b062-11e8-885d-f497d172e04b.png)
如图， 登录模块有一个滑块验证，该如何写配置文件

**Comment by mizhdi** [comment]
![image](https://user-images.githubusercontent.com/3582887/45020965-e9c3b180-b062-11e8-808f-dc5345f21d98.png)

**Comment by SamuelZhaoY** [comment]
@mizhdi 参考hook.js 目前这里 需要手动调用底层指令
