### ISSUE TITLE
 Support for ocr-based mode of operation

### ISSUE THREAD

**Issue by xudafeng** [macacajs/NoSmoke#63]
purpose: Easier to get elements and click locations for crawling.

- [x] Add ocr support option
- [x] Stability test @SamuelZhaoY
- [x] 使用文档和示例 @SamuelZhaoY

**Comment by SamuelZhaoY** [comment]
OCR 已完成主要开发，文档完善中

**Comment by xudafeng** [comment]
@SamuelZhaoY 稳定性怎么样了

**Comment by xudafeng** [comment]
## 未完成

https://github.com/macacajs/NoSmoke/issues/67

**Comment by SamuelZhaoY** [comment]
设备相对像素ratio 处理:

https://i.stack.imgur.com/c6l4f.png
