### ISSUE TITLE
ubnetu系统上执行 nosmoke，macaca server端错误uiautomator-client.js:119:12 [master] pid:2487 proxy.send except: Error: connect ECONNREFUSED 127.0.0.1:9001

### ISSUE THREAD

**Issue by liufeiflying** [macacajs/NoSmoke#82]
## 在ubnetu系统上执行 nosmoke，macaca server端报以下错误
>> responseHandler.js:11:12 [master] pid:2487 Recieve HTTP Request from Client[2019-04-17 15:44:51]: method: POST url: /wd/hub/session/e0e6fa2e-68ed-423b-b2db-f669ea73eaeb/actions, jsonBody: {"actions":[{"type":"tap","x":361,"y":1003.5}]}
>> proxy.js:56:14 [master] pid:2487 Proxy: /wd/hub/session/:sessionId/accept_alert:POST to http://127.0.0.1:9001/wd/hub/session/:sessionId/accept_alert:POST with body: {}
>> proxy.js:64:22 [master] pid:2487 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
>> proxy.js:64:22 [master] pid:2487 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
>> proxy.js:64:22 [master] pid:2487 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
>> proxy.js:64:22 [master] pid:2487 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
>> proxy.js:64:22 [master] pid:2487 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
>> proxy.js:64:22 [master] pid:2487 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
>> proxy.js:64:22 [master] pid:2487 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
>> proxy.js:64:22 [master] pid:2487 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
>> proxy.js:64:22 [master] pid:2487 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
>> proxy.js:64:22 [master] pid:2487 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
>> proxy.js:64:22 [master] pid:2487 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
>> uiautomator-client.js:119:12 [master] pid:2487 proxy.send except: Error: connect ECONNREFUSED 127.0.0.1:9001
>> proxy.js:56:14 [master] pid:2487 Proxy: /wd/hub/session/e0e6fa2e-68ed-423b-b2db-f669ea73eaeb/actions:POST to http://127.0.0.1:9001/wd/hub/session/e0e6fa2e-68ed-423b-b2db-f669ea73eaeb/actions:POST with body: {"actions":[{"type":"tap","x":361,"y":1003.5}]}
>> proxy.js:64:22 [master] pid:2487 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
>> proxy.js:64:22 [master] pid:2487 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001

**Comment by paradite** [comment]
please raise the issue here, following the issue format:
https://github.com/alibaba/macaca/issues/new
