### ISSUE TITLE
取ocr结果数组方法不安全导致crash，取screenshoots路径不全（没有拼上root.crawlingDateStamp）导致取img失败crash

### ISSUE THREAD

**Issue by LeonYin945** [macacajs/NoSmoke#85]
![image](https://user-images.githubusercontent.com/13748427/70888538-8cffc680-201b-11ea-819f-4b78c5232a3d.png)
refresh screen result: {"id":"page_1","bbox":{"x0":"0","y0":"0","x1":"828","y1":"1792"},"lines":[{"line":[]},{"line":[]},......
取ocr结果数组方法不安全，ocr出来的line有空数组的情况，导致crash

**Comment by LeonYin945** [comment]
![Uploading image.png…]()
Error: ENOENT: no such file or directory, open 'reports/screenshots/19357f67-12e3-451f-b684-f133d2ea031d_0.png'

**Comment by SamuelZhaoY** [comment]
感谢回复，会尽快处理

**Comment by SamuelZhaoY** [comment]
```
Error: ENOENT: no such file or directory, open 'reports/screenshots/19357f67-12e3-451f-b684-f133d2ea031d_0.png'，中间未拼接上root.crawlingDateStamp导致取img crash
```
第二个问题 应该是别的原因，代码中有对crawlingDateStamp 路径中进行拼接. 
![image](https://user-images.githubusercontent.com/8198256/71052882-ade52a80-2187-11ea-8c96-18ef686e08cd.png)
